<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="dongcai_block_test.dongcai_block_tests.TestBlockStorage-20170929151326" skipped="0" tests="2" time="0.226">
	<testcase classname="dongcai_block_test.dongcai_block_tests.TestBlockStorage" name="test_view" time="0.115"/>
	<testcase classname="dongcai_block_test.dongcai_block_tests.TestBlockStorage" name="test_block_view" time="0.110">
		<error message="block_view() takes exactly 2 arguments (1 given)" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/home/tangr/work/f10_project/f10_new_block/src/unittest/python/dongcai_block_test/dongcai_block_tests.py", line 38, in test_block_view
    block_views = block_read.block_view(self._block_data)
TypeError: block_view() takes exactly 2 arguments (1 given)
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[{u'Code': u'SZ000488', u'PlateName': u'\u6982\u5ff5\u677f\u5757', u'Name': u'\u6668\u9e23\u7eb8\u4e1a', u'TypeName': u'AB\u80a1', u'SysCode': u'DG00498', u'Date': u'2017-09-27', u'TypeZm': u'A'}
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
